version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sqlserver
    hostname: sqlserver
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - commerce-net

  api:
    build:
      context: ./api-admin-mercado-gestion
      dockerfile: WebApplication1/Dockerfile
    container_name: api-commerce
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - minio
    networks:
      - commerce-net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio_server2
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - commerce-net

  api-web:
    build:
      context: api-web
      dockerfile: Dockerfile
    container_name: api-web
    env_file:
      - .env
    ports:
      - 8082:80
    depends_on:
      - db
      - minio
    networks:
      - commerce-net
      
  web:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: web-commerce
    ports:
      - 3001:3000
    networks:
      - commerce-net
      
volumes:
  sql_data:
  minio_data:

networks:
  commerce-net:
